### ISSUE TITLE
config.json

### ISSUE THREAD

**Issue by torsina** [discord-movie-database/DMDb#1]
hello, I saw you stopped working on the Imdb bot. The server I'm in(9i) really loved it. We want to make it work for us again. Problem is I don't really know what was in your config file and other possible files that are not in the repo. Could you please add it without the auth token ?
Thank you

**Comment by Dumblings** [comment]
config.json:
```json
{
    "token": {
        "bot": "",
        "bitly": ""
    },
    "db": {
        "host": "localhost",
        "port": "28015"
    },
    "prefix": "",
    "ownerid": "",
    "shardCount": 1,
    "errorChannel": ""
}
```

**EDIT: [I've added a config template.](https://github.com/Dumplingsr/DMDb/tree/v1/config-template.json)**
